name: 'Check for and build a new commit'

on:
  workflow_call:
    inputs:
      branch-type:
        required: true
        type: string
    secrets:
      debian-secret-key:
        required: false
      debian-secret-iv:
        required: false

env:
  GH_TOKEN: ${{ github.token }}
  BRANCH_STABLE: ${{ vars.BRANCH_STABLE }}
  BRANCH_NEXT_STABLE: ${{ vars.BRANCH_NEXT_STABLE }}

jobs:
  check-and-build-commit:
    name: Check for and build a new commit
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        id: install
        run: |
          set -e -u -x

          sudo /usr/bin/env DEBIAN_FRONTEND=noninteractive \
              apt-get install --no-install-recommends --yes \
              devscripts \
              osc
      - name: Set Up Git
        id: setup-git
        run: |
          set -e -u -x

          token=$(echo -n "x-access-token:${{ secrets.GITHUB_TOKEN }}" | base64)
          git config --global http.https://github.com/.extraHeader "Authorization: Basic ${token}"

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.nflink.com"

      - name: Checkout
        id: checkout
        env:
          GH_REPOSITORY: ${{ github.repository }}
        run: |
          set -e -u -x

          git clone "https://github.com/${GH_REPOSITORY}" "${GITHUB_WORKSPACE}/debian-build"
          cd "${GITHUB_WORKSPACE}/debian-build"

          BRANCH_TYPE="${{ inputs.branch-type }}"
          if test "${BRANCH_TYPE}" = "master"; then
              branch="master"
          elif test "${BRANCH_TYPE}" = "stable"; then
              branch="${BRANCH_STABLE}"
          elif test "${BRANCH_TYPE}" = "next-stable"; then
              branch="${BRANCH_NEXT_STABLE}"
          else
              echo "Invalid branch type: ${BRANCH_TYPE}"
              exit 1
          fi

          git branch --remote | \
              grep --extended-regexp "origin/debian/dist/.+/${branch}" | \
              sed 's:origin/::' | \
              xargs -I {} git checkout -b {} origin/{}
          git checkout master

      - name: Check for and build a new commit
        id: check-and-build
        env:
          DEBIAN_SECRET_KEY: ${{ secrets.debian-secret-key }}
          DEBIAN_SECRET_IV: ${{ secrets.debian-secret-iv }}
        run: |
          "${GITHUB_WORKSPACE}/debian-build/check-and-build-latest-commit.sh" "${GITHUB_WORKSPACE}" ${{ inputs.branch-type }}
      - name: Cleanup
        id: cleanup
        run: |
          set -e -u -x

          git config --global --unset http.https://github.com/.extraHeader
