name: 'Check for and build a new commit on the master branch'

on:
  workflow_call:
  schedule:
    - cron: '21 * * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-check-and-build-latest-commit:
    uses: ./.github/workflows/check-and-build-latest-commit.yaml
    with:
      branch-type: master
